- hosts: supergo.test
  remote_user: deploy
  tasks:
    - name: stop container
      shell: docker stop {{ server_name }} || true

    - name: remove container
      shell: docker rm {{ server_name }} || true

    - name: remove image
      shell: docker rmi $( docker images -f reference={{ registry }}/{{ server_name }} ) || true

    - name: run supergo-hubot
      shell: docker run -ti
          --name {{ server_name }} -p {{ server_port }}:8081 
          -v /var/hubot/shell:/supergo/bash/handlers 
          -d {{ registry }}/{{ server_name }}:{{ version }} 
          bash -c 'npm run hubot {{ password }}'

    - name: wait 30 seconds
      shell: sleep 30s

    - name: check uri
      uri:
        url: http://localhost:{{ server_port }}/hubot/ping
        method: GET
        timeout: 30
