- hosts: supergo.test
  remote_user: deploy
  tasks:
    - name: stop container
      shell: docker stop {{ name }} || true

    - name: remove image
      shell: docker rmi $(docker images -f reference={{ registry }}/{{ name }}) || true

    - name: run supergo-hubot
      shell: docker run -ti
          --name {{ name }} -p {{ port }}:8001 
          -d {{ registry }}/{{ name }}:{{ version }} 
          bash -c 'npm run hubot {{ password }}'
