- hosts: supergo.test
  remote_user: deploy
  tasks:
    - name: stop container
      shell: docker stop {{ name }} || true

    - name: remove container
      shell: docker rm $( docker ps -f name={{ name }} ) || true

    - name: remove image
      shell: docker rmi $( docker images -f reference={{ registry }}/{{ name }} ) || true

    - name: run supergo-hubot
      shell: docker run -ti
          --name {{ name }} -p {{ port }}:8081 
          -d {{ registry }}/{{ name }}:{{ version }} 
          bash -c 'npm run hubot {{ password }}'
          
    - name: check uri
      shell: sleep 5
      uri:
        url: http://localhost:{{ port }}/hubot/ping
        method: POST
        timeout: 30
